services:
  ztlog-web-console:
    image: zoetrope56/ztlog-web-console:latest
    container_name: ztlog-web-console
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
